name: 'Update README'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  recent-activity:
    name: 'Update README with latest activity'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/Checkout@v3
      - name: 'Update README.md from TEMPLATE.md'
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: '.github/update-readme.config.yml'
  
          
          base: ""
          
          config_octicon: yes
          
          plugin_stargazers: yes
          plugin_contributors: yes
